[package]
name = "tasklist-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.1"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["fmt"] }
tasklists = { path = "../libtasklist" }
